import { OptionType } from "paca-ui/src/stories/organisms/branchEditForm/BranchEditForm";

const locations = [
  "Catia",
  "23 de enero",
  "Nueva Caracas",
  "Propatria",
  "Lomas de Urdaneta",
  "Casalta",
  "La Silsa",
  "La Moran",
  "El Atlántico",
  "Los Magallanes",
  "Los Frailes",
  "Alta Vista",
  "Ruperto Lugo",
  "Lídice",
  "Los Mecedores",
  "Gramoven",
  "Manicomio",
  "Los Robles",
  "Urdaneta",
  "Terrazas de Guaicaipuro",
  "Vista Al Mar",
  "Oropeza Castillo",
  "La Cortada",
  "Nuevo Horizonte",
  "Vista Hermosa",
  "El Refugio",
  "Barrio Obrero",
  "Cutira",
  "Caribe",
  "Barrio El Amparo",
  "Simón Bolívar",
  "Brisas de Propatria",
  "Las Tunitas",
  "Barrio Niño Jesús",
  "Luis Hurtado Higuera",
  "Sabana del Blanco",
  "Niño Jesús",
  "Boquerón",
  "Camino de los Españoles",
  "El Polvorín",
  "San Martín",
  "Quinta Crespo",
  "Artigas",
  "Vista Alegre",
  "Bella Vista",
  "Vista Alegre",
  "Colinas de Vista Alegre",
  "La Yaguara",
  "Zona Industrial de La Yaguara",
  "El Algodonal",
  "Carapa",
  "Carapita",
  "Antímano",
  "Washington",
  "Las Fuentes",
  "La Paz",
  "El Paraíso",
  "El Pinar",
  "Loira",
  "La Paz",
  "Montalbán",
  "Juan Pablo II",
  "La Vega",
  "Los Paraparos",
  "Los Eucaliptos",
  "Las Adjuntas",
  "Macarao",
  "Caricuao",
  "Mamera",
  "Roca Tarpeya",
  "Los Laureles",
  "Barrio Villa Zoila",
  "Las Luces",
  "Prados de María",
  "Los Totumo",
  "Barrio Los Sin Techo",
  "Barrio Guzmán Blanco",
  "Barrio La Ceiba",
  "Los Laureles",
  "Monte Alto",
  "Los Nísperos",
  "El Guamal",
  "Barrio El Cafetal",
  "Los Nísperos 2",
  "La Pericosa",
  "Altos de Irapa",
  "González Cabrera",
  "El Sifón",
  "Cristo es La Puerta",
  "Los Álamos",
  "Los Haticos",
  "Las Casitas",
  "Los Mangos",
  "Terrazas de Caricuao",
  "Juan XXIII",
  "La Colmena",
  "Urb Cultura",
  "Sin Ley",
  "Caño Amarillo",
  "Santa Rosa",
  "Barrio Sucre",
  "Barrio Santa Rosa",
  "Urdaneta",
  "Simón Bolívar",
  "Urdaneta",
  "Propatria",
  "Brisas de Propatria",
  "Casalta",
  "El Cardonal",
  "Pérez Bonalde",
  "El Limón",
  "El Amparo",
  "Los Pasajes",
  "Federico Quiroz",
  "Tacagua Vieja Tamanaquito",
  "Plan de Manzano",
  "Olivett",
  "Mulatal",
  "Mario Briceño Iragorry",
  "Las Torres",
  "Unión",
  "Quebradita",
  "13 de septiembre",
  "18 de octubre",
  "Buenos Aires",
  "La Baranda",
  "Las Escaleras de la 1 a la 7",
  "Las Marías",
  "San Miguel",
  "Coche",
  "Acosta Carles",
  "José Gregorio Hernández",
  "Los Cerritos",
  "Luis Felipe",
  "El Silencio",
  "Catedral",
  "La Hoyada",
  "Altagracia",
  "La Pastora",
  "San José",
  "San Juan",
  "Santa Teresa",
  "Santa Rosalía",
  "La Candelaria",
  "Cotiza",
  "El Conde",
  "San Agustín del Sur",
  "San Agustín del Norte",
  "El Manguito",
  "La Ceiba",
  "Hornos de Cal",
  "La Charneca",
  "San Bernardino",
  "Guaicaipuro",
  "El Panteón",
  "Tienda Honda",
  "Foro Libertador",
  "Los Caobos/Plaza Venezuela",
  "Santa Rosa",
  "Quebrada Honda",
  "Chapellín",
  "Los Cedros",
  "San Antonio de Sabana Grande",
  "Simón Rodríguez",
  "Maripérez",
  "La Colina",
  "Las Palmas",
  "Las Lomas",
  "San Rafael",
  "La Florida",
  "Alta Florida",
  "Bucaral",
  "Country Club",
  "Sabana Grande",
  "Bello Monte",
  "La Campiña",
  "Chapellin",
  "Barrio Parate Bueno",
  "Barrio Nuevo Callejon",
  "Barrio El Eraso",
  "Barrio Andrés Bello",
  "Country Club",
  "Sabana Grande",
  "Bello Monte",
  "La Campiña",
  "Alta Florida",
  "El Bosque",
  "El Rosal",
  "Estado Leal",
  "El Retiro",
  "Sans-Souci",
  "Las Delicias de Sabana Grande",
  "Bello Campo",
  "El Pedregal",
  "San Marino",
  "Campo Alegre",
  "Chacao",
  "Altamira",
  "Los Palos Grandes",
  "Pajaritos",
  "La Castellana",
  "La Floresta",
  "El Dorado",
  "Santa Eduvigis",
  "Sebucán",
  "Santa María",
  "Terrazas del Ávila",
  "Petare",
  "Lebrún",
  "Campo Rico",
  "El Marqués",
  "La Urbina",
  "El Dorado (de Chacao)",
  "San Miguel",
  "La Guairita",
  "Palo Verde",
  "Lomas del Ávila",
  "Miranda",
  "El Dorado (de Sucre)",
  "Barrio La Manguera",
  "Barrio Bello Campo",
  "Barrio La Cruz de Chacao",
  "Barrio La Castellana",
  "Barrio Bucaral",
  "Barrio Hoyo de la Puerta",
  "Barrio San José",
  "Hoyo de las Delicias",
  "Barrio La Manguera",
  "Barrio Pedregal",
  "Barrio San Miguel",
  "Boleíta Sur",
  "Boleíta Norte",
  "La Lucha",
  "La Carlota",
  "Santa Cecilia",
  "Campo Claro",
  "Los Ruíces",
  "Montecristo",
  "Los Chorros",
  "Los Dos Caminos",
  "Lomas de Los Chorros",
  "El Amparo",
  "Buena Vista",
  "Brisas de Petare",
  "Los Cortijos",
  "La California Oeste",
  "La California Norte",
  "La California Sur",
  "Colinas de La California",
  "Macaracuay",
  "Barrio La Lucha",
  "El Llanito",
  "Horizonte",
  "El Marqués",
  "Los Chaguaramos",
  "Colinas de los Chaguaramos",
  "Santa Mónica",
  "Colinas de Santa Mónica",
  "Las Acacias",
  "Colinas de las Acacias",
  "Terrazas de Las Acacias",
  "Paseo Los Próceres",
  "Ciudad Universitaria (parte de la Urb Valle Abajo)",
  "Jardín Botánico",
  "Cumbres de Curumo",
  "Los Rosales",
  "Valle Abajo",
  "La Rinconada",
  "El Valle",
  "Coche",
  "Cementerio",
  "Fuerte Tiuna",
  "Ciudad Tiuna",
  "El Triángulo",
  "Barrio Las Malvilas",
  "Sabana Grande (de La Bandera)",
  "San Antonio (de La Bandera)",
  "Colinas de Bello Monte",
  "Ciudad Tamanaco",
  "Las Mercedes",
  "Chuao",
  "Lomas del Mirador",
  "Valle Arriba",
  "Santa Fe",
  "Los Campitos",
  "Prados del Este",
  "Alto Prado",
  "Manzanares",
  "El Peñón",
  "La Trinidad",
  "La Tahona",
  "La Bonita",
  "Monterrey",
  "Los Samanes",
  "San Román",
  "Santa Rosa de Lima",
  "Caurimare",
  "El Cafetal",
  "San Luis",
  "Santa Sofía",
  "Santa Paula",
  "Santa Inés",
  "Santa Clara",
  "Santa Ana",
  "Cerro Verde",
  "Los Naranjos",
  "El Cigarral",
  "La Boyera",
  "Los Pinos",
  "La Cabaña",
  "Alto Hatillo",
  "El Hatillo",
  "Los Geranios",
  "La Lagunita",
  "Lomas de La Lagunita",
  "El Placer",
  "El Guayabao",
  "El Volcán",
  "La Unión",
  "Sartanejas",
  "Hoyo de la Puerta",
  "La Trinidad",
  "Guaicay",
  "La Ciudadela",
  "Sorocaima",
  "Los Pomelos",
  "Terrazas del Club Hípico",
  "Loma Larga",
];
const sorted = locations.sort();
const result: OptionType[] = sorted.map((item) => ({
  label: item,
  value: item,
}));

export default result;
