name: Business Frontend Deployment

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Image
    runs-on: [self-hosted]
    outputs:
      BUILD_NUMBER: ${{steps.build-number.outputs.BUILD_NUMBER}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEM }}

      - name: Build Number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%-d.%-m.%Y.%-H.%-M.%-S')" >> $GITHUB_OUTPUT

      - name: Run docker build
        id: next-build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/paca-business:${{steps.build-number.outputs.BUILD_NUMBER}} -t ${{ secrets.DOCKERHUB_USERNAME }}/paca-business:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/paca-business:${{steps.build-number.outputs.BUILD_NUMBER}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/paca-business:latest

  cd:
    name: Deployment into server
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: deploy new business app image
        if: ${{ always() }}
        run: |
          docker rm -f paca-business; 
          docker run -d --network host --name paca-business ${{ secrets.DOCKERHUB_USERNAME }}/paca-business:latest