name: Main Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  npm-build:
    name: Build App
    runs-on: [self-hosted, paca]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git SubModule Update
        run: git submodule update --init --recursive

      - name: Build App
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build